import Foundation

// Pure admission/acceptance state machine. The isolated service supplies verified
// reader/transport metadata; no shipped application depends on this target.
struct DesktopUsageOwner: Equatable, Sendable, CustomStringConvertible, CustomDebugStringConvertible
{
  let accountFingerprint: String
  let organizationFingerprint: String

  var description: String { "DesktopUsageOwner(redacted)" }
  var debugDescription: String { description }

  var isValid: Bool {
    [accountFingerprint, organizationFingerprint].allSatisfy { value in
      value.utf8.count == 64
        && value.utf8.allSatisfy { (48...57).contains($0) || (97...102).contains($0) }
    }
  }
}

struct DesktopUsageContext: Equatable, Sendable {
  let owner: DesktopUsageOwner
  // Opaque revision generated by the reader, never a credential or its hash.
  // Must change on sign-out, account/org switching (including A -> B -> A), or renewal.
  let generation: UUID
  let expiresAt: Date
  let hasProfileScope: Bool
}

struct DesktopUsageRequest: Equatable, Sendable {
  let id: UUID
  let context: DesktopUsageContext
  let startedAt: Date
  let deadline: Date
}

struct DesktopUsageObservation: Equatable, Sendable {
  let owner: DesktopUsageOwner
  let capturedAt: Date
  let values: DesktopUsageValues
}

enum DesktopUsagePermission: Sendable {
  case notRequested
  case allowed
  case denied
}

enum DesktopUsageState: String, Sendable {
  case consentRequired
  case permissionDenied
  case identityUnavailable
  case contextChanged
  case credentialExpired
  case missingScope
  case ready
  case requesting
  case current
  case stale
  case resetElapsed
  case waitingForDesktopRenewal
  case accessDenied
  case rateLimited
  case temporaryFailure
  case timedOut
  case invalidResponse
  case identityMismatch
  case invalidClock
  case serviceWaitUnavailable
  case persistenceUnavailable
  case waitingForNextRefresh
  case waitingForProvider
}

enum DesktopUsageReply: Sendable {
  // The transport must verify the profile with the same exact credential
  // lease as this usage request, disable redirects/cache, and bound bytes in transit.
  case response(
    status: Int, profileOwner: DesktopUsageOwner?, serverDate: Date?,
    cacheAge: TimeInterval?, retryAfter: Date?, body: Data)
  case networkFailure
  case timeout
  case unsupportedRateLimit
}

enum DesktopAuthRefusal: String, Codable, Sendable {
  case waitingForDesktopRenewal
  case accessDenied

  var state: DesktopUsageState {
    switch self {
    case .waitingForDesktopRenewal: .waitingForDesktopRenewal
    case .accessDenied: .accessDenied
    }
  }
}

// Restart metadata only. No observation, owner, credential or credential revision.
struct DesktopThrottleRecord: Codable, Equatable, Sendable {
  var schemaVersion = 1
  var recordedAt: Date
  var lastAttemptAt: Date? = nil
  var localNextAllowedAt: Date? = nil
  var successfulNextAllowedAt: Date? = nil
  var serviceNotBefore: Date? = nil
  var unsupportedServiceWait = false
  var failureCount = 0
  var interruptedUntil: Date? = nil
  var authRefusal: DesktopAuthRefusal? = nil
  var authRefusalExpiresAt: Date? = nil

  var isValid: Bool {
    let reference = max(recordedAt, lastAttemptAt ?? recordedAt)
    return schemaVersion == 1 && (0...5).contains(failureCount)
      && [
        recordedAt, lastAttemptAt, localNextAllowedAt, successfulNextAllowedAt,
        serviceNotBefore, interruptedUntil, authRefusalExpiresAt,
      ].compactMap { $0 }.allSatisfy {
        $0.timeIntervalSince1970.isFinite && $0.timeIntervalSince1970 > 0
      }
      && (interruptedUntil == nil || lastAttemptAt != nil)
      && (authRefusalExpiresAt == nil || authRefusal != nil)
      && (localNextAllowedAt.map { $0.timeIntervalSince(reference) <= 900 } ?? true)
      && (successfulNextAllowedAt.map { $0.timeIntervalSince(reference) <= 300 } ?? true)
      && (interruptedUntil.map {
        guard let lastAttemptAt else { return false }
        return (0...900).contains($0.timeIntervalSince(lastAttemptAt))
      } ?? true)
      && (serviceNotBefore.map {
        $0.timeIntervalSince(recordedAt) <= DesktopUsageCoordinator.maximumSupportedServiceWait
      } ?? true)
  }
}

struct DesktopUsageCoordinator: Sendable {
  static let requestTimeout: TimeInterval = 30
  static let refreshInterval: TimeInterval = 5 * 60
  static let observationMaximumAge: TimeInterval = 15 * 60
  // Preserve finite service deadlines, including waits longer than one year.
  static let maximumSupportedServiceWait: TimeInterval = 100 * 366 * 86400

  private(set) var permission: DesktopUsagePermission = .notRequested
  private(set) var state: DesktopUsageState = .consentRequired
  private(set) var observation: DesktopUsageObservation?
  private(set) var activeRequest: DesktopUsageRequest?
  private(set) var lastAttemptAt: Date?
  var nextAllowedAt: Date? {
    return [localNextAllowedAt, successfulNextAllowedAt, serviceNotBefore].compactMap { $0 }.max()
  }
  private var localNextAllowedAt: Date?
  private var successfulNextAllowedAt: Date?
  private var serviceNotBefore: Date?
  private var unsupportedServiceWait = false
  private var interruptedUntil: Date?
  private var authRefusal: DesktopAuthRefusal?
  private var authRefusalGeneration: UUID?
  private var authRefusalExpiresAt: Date?
  private var recheckRequestID: UUID?
  private var context: DesktopUsageContext?
  private var suspendedState: DesktopUsageState?
  private var rejectedGenerations: [(generation: UUID, state: DesktopUsageState)] = []
  private var issuedRequests: [DesktopUsageRequest] = []
  private var failureCount = 0
  private var latestClock: Date?

  mutating func restoreThrottle(_ record: DesktopThrottleRecord, now: Date) -> Bool {
    guard record.isValid, Self.validDate(now), lastAttemptAt == nil else { return false }
    lastAttemptAt = record.lastAttemptAt
    localNextAllowedAt = record.localNextAllowedAt
    successfulNextAllowedAt = record.successfulNextAllowedAt
    serviceNotBefore = record.serviceNotBefore
    unsupportedServiceWait = record.unsupportedServiceWait
    failureCount = record.failureCount
    authRefusal = record.authRefusal
    authRefusalGeneration = nil
    authRefusalExpiresAt = record.authRefusalExpiresAt
    latestClock = record.recordedAt
    // No observation is restored. An interrupted attempt gets a bounded quiet
    // period, not an immediate retry or a permanently unrecoverable pending bit.
    if let pending = record.interruptedUntil { extendDelay(until: pending) }
    _ = checkClock(now)
    return true
  }

  func throttleRecord(now: Date) -> DesktopThrottleRecord {
    DesktopThrottleRecord(
      recordedAt: Self.validDate(now)
        ? max(now, latestClock ?? now) : latestClock ?? Date(timeIntervalSince1970: 1),
      lastAttemptAt: lastAttemptAt, localNextAllowedAt: localNextAllowedAt,
      successfulNextAllowedAt: successfulNextAllowedAt, serviceNotBefore: serviceNotBefore,
      unsupportedServiceWait: unsupportedServiceWait, failureCount: failureCount,
      interruptedUntil: interruptedUntil, authRefusal: authRefusal,
      authRefusalExpiresAt: authRefusalExpiresAt)
  }

  // Called before any suspension after HTTP, so known restrictions can be made
  // durable even if context verification hangs or consent changes meanwhile.
  mutating func recordServiceRestriction(
    _ request: DesktopUsageRequest, reply: DesktopUsageReply, now: Date
  ) {
    guard issuedRequests.contains(request) else { return }
    let receivedClock = Self.validDate(now) ? now : request.startedAt
    let conservativeClock = max(latestClock ?? request.startedAt, receivedClock)
    switch reply {
    case .response(let status, _, _, _, _, _) where status == 401 || status == 403:
      let refusal: DesktopAuthRefusal = status == 401 ? .waitingForDesktopRenewal : .accessDenied
      authRefusal = refusal
      authRefusalGeneration = request.context.generation
      authRefusalExpiresAt = request.context.expiresAt
      reject(request.context.generation, state: refusal.state)
      if context?.generation == request.context.generation { observation = nil }
    case .unsupportedRateLimit:
      unsupportedServiceWait = true
      extendDelay(until: conservativeClock.addingTimeInterval(900))
    case .response(let status, _, _, _, let retryAfter, _) where status == 429 || status == 503:
      extendServiceDelay(until: conservativeClock.addingTimeInterval(60))
      if let retryAfter, Self.validDate(retryAfter) {
        if retryAfter.timeIntervalSince(conservativeClock) > Self.maximumSupportedServiceWait {
          unsupportedServiceWait = true
          extendDelay(until: conservativeClock.addingTimeInterval(900))
        } else {
          extendServiceDelay(until: retryAfter)
        }
      }
    default: break
    }
  }

  // Only explicit user interaction may change this; a polling caller cannot prompt.
  mutating func setPermission(_ permission: DesktopUsagePermission) {
    self.permission = permission
    observation = nil
    activeRequest = nil
    context = nil
    suspendedState = nil
    state = permission == .allowed ? .ready : permissionState
    // Consent is not credential renewal and cannot clear refusals or service backoff.
  }

  // Keep prior values quarantined in memory, not displayable, until the reader
  // proves an owner again. This does not accept a response from an unverified read.
  mutating func suspendContext(now: Date) {
    guard checkClock(now) else { return }
    activeRequest = nil
    if suspendedState == nil {
      suspendedState = state == .requesting ? .contextChanged : state
    }
    state = .identityUnavailable
  }

  mutating func begin(
    context newContext: DesktopUsageContext?, now: Date, userRequestedRecheck: Bool = false
  ) -> DesktopUsageRequest? {
    guard checkClock(now) else { return nil }
    guard synchronize(newContext, now: now) else { return nil }
    let recheck = userRequestedRecheck && (authRefusal != nil || unsupportedServiceWait)
    guard !unsupportedServiceWait || recheck else {
      state = .serviceWaitUnavailable
      return nil
    }
    if let activeRequest {
      guard now >= activeRequest.deadline else { return nil }
      self.activeRequest = nil
      fail(.timedOut, now: now)
      return nil
    }
    if !recheck, let context, let rejection = rejection(for: context.generation) {
      state = rejection
      return nil
    }
    let deadline = [localNextAllowedAt, successfulNextAllowedAt, serviceNotBefore].compactMap { $0 }
      .max()
    guard deadline.map({ now >= $0 }) ?? true, let context else {
      if observation == nil, state == .contextChanged || state == .ready {
        state =
          serviceNotBefore.map { now < $0 } == true
          ? .waitingForProvider : .waitingForNextRefresh
      }
      return nil
    }
    let request = DesktopUsageRequest(
      id: UUID(), context: context, startedAt: now,
      deadline: now.addingTimeInterval(Self.requestTimeout))
    activeRequest = request
    issuedRequests.append(request)
    issuedRequests = Array(issuedRequests.suffix(8))
    lastAttemptAt = now
    localNextAllowedAt = now.addingTimeInterval(recheck ? 900 : 60)
    recheckRequestID = recheck ? request.id : nil
    interruptedUntil = now.addingTimeInterval(15 * 60)
    state = .requesting
    return request
  }

  mutating func complete(
    _ request: DesktopUsageRequest, reply: DesktopUsageReply,
    context newContext: DesktopUsageContext?, now: Date
  ) {
    // Cancelled replies cannot replace values. A known 429 may only extend the
    // service-wide delay, even when an account change revoked its request.
    guard let issuedIndex = issuedRequests.firstIndex(of: request) else { return }
    recordServiceRestriction(request, reply: reply, now: now)
    issuedRequests.remove(at: issuedIndex)
    if activeRequest == request { interruptedUntil = nil }
    guard activeRequest == request else { return }
    if newContext == nil {
      suspendContext(now: now)
      return
    }
    guard checkClock(now), synchronize(newContext, now: now) else { return }
    guard activeRequest == request, context == request.context else { return }
    activeRequest = nil
    guard now < request.deadline else {
      fail(.timedOut, now: now)
      return
    }
    switch reply {
    case .unsupportedRateLimit:
      state = .serviceWaitUnavailable
    case .networkFailure:
      fail(.temporaryFailure, now: now)
    case .timeout:
      fail(.timedOut, now: now)
    case .response(
      let status, let profileOwner, let serverDate, let cacheAge, _, let body):
      if status == 401 || status == 403 {
        observation = nil
        state = status == 401 ? .waitingForDesktopRenewal : .accessDenied
        return
      }
      if status == 429 {
        fail(unsupportedServiceWait ? .serviceWaitUnavailable : .rateLimited, now: now)
        return
      }
      guard status == 200 else {
        fail((500...599).contains(status) ? .temporaryFailure : .invalidResponse, now: now)
        return
      }
      if let rejection = rejection(for: request.context.generation), recheckRequestID != request.id
      {
        observation = nil
        state = rejection
        return
      }
      guard profileOwner == request.context.owner else {
        observation = nil
        state = .identityMismatch
        reject(request.context.generation, state: state)
        return
      }
      guard let serverDate, Self.validDate(serverDate),
        serverDate >= request.startedAt.addingTimeInterval(-5),
        serverDate <= now.addingTimeInterval(5),
        now.timeIntervalSince(serverDate) <= Self.requestTimeout + 5,
        cacheAge.map({ $0.isFinite && $0 == 0 }) ?? true,
        observation.map({ min(serverDate, now) > $0.capturedAt }) ?? true,
        let values = try? DesktopUsagePayloadDecoder.decode(body, observedAt: min(serverDate, now)),
        let reset = values.weekly.resetAt, reset > now
      else {
        fail(.invalidResponse, now: now)
        return
      }
      observation = DesktopUsageObservation(
        owner: request.context.owner, capturedAt: min(serverDate, now),
        values: Self.currentWindows(values, now: now))
      if recheckRequestID == request.id {
        authRefusal = nil
        authRefusalGeneration = nil
        authRefusalExpiresAt = nil
        rejectedGenerations.removeAll { $0.generation == request.context.generation }
        unsupportedServiceWait = false
        recheckRequestID = nil
      }
      failureCount = 0
      state = .current
      successfulNextAllowedAt = min(reset, now.addingTimeInterval(Self.refreshInterval))
    }
  }

  // Rechecking context is required even during backoff or a cached display read.
  mutating func currentObservation(
    context newContext: DesktopUsageContext?, now: Date
  ) -> DesktopUsageObservation? {
    guard checkClock(now), synchronize(newContext, now: now), let observation,
      observation.capturedAt <= now,
      now.timeIntervalSince(observation.capturedAt) <= Self.observationMaximumAge,
      let reset = observation.values.weekly.resetAt, reset > now
    else { return nil }
    return DesktopUsageObservation(
      owner: observation.owner, capturedAt: observation.capturedAt,
      values: Self.currentWindows(observation.values, now: now))
  }

  private var permissionState: DesktopUsageState {
    permission == .denied ? .permissionDenied : .consentRequired
  }

  private mutating func synchronize(_ newContext: DesktopUsageContext?, now: Date) -> Bool {
    guard permission == .allowed else {
      invalidate(permissionState)
      return false
    }
    guard let newContext, newContext.owner.isValid else {
      invalidate(.identityUnavailable)
      return false
    }
    if let suspendedState {
      self.suspendedState = nil
      state = suspendedState
    }
    if newContext != context {
      let sameOwner = newContext.owner == context?.owner
      activeRequest = nil
      if !sameOwner { observation = nil }
      if let context, newContext.generation != context.generation || !sameOwner {
        // Renewal can retry after the normal attempt floor, but never bypasses
        // a failure backoff or a provider's Retry-After deadline.
        successfulNextAllowedAt = nil
      }
      context = newContext
      state = .contextChanged
    }
    guard Self.validDate(newContext.expiresAt), newContext.expiresAt > now else {
      observation = nil
      activeRequest = nil
      state = .credentialExpired
      return false
    }
    guard newContext.hasProfileScope else {
      observation = nil
      activeRequest = nil
      state = .missingScope
      return false
    }
    if let authRefusal {
      // A new process's random generation is not proof of renewal. Bind the
      // restored refusal only after a valid read, then require a later change.
      if authRefusalGeneration == nil, let expiry = authRefusalExpiresAt,
        expiry != newContext.expiresAt
      {
        // A different expiry proves this is not the rejected lease. Equality
        // proves nothing about the owner; explicit recheck covers that ambiguity.
        self.authRefusal = nil
        authRefusalExpiresAt = nil
      } else if authRefusalGeneration == nil {
        authRefusalGeneration = newContext.generation
      }
      if authRefusalGeneration == newContext.generation {
        reject(newContext.generation, state: authRefusal.state)
      } else if rejection(for: newContext.generation) == nil {
        self.authRefusal = nil
        authRefusalGeneration = nil
        authRefusalExpiresAt = nil
      }
    }
    if let rejection = rejection(for: newContext.generation) {
      observation = nil
      state = rejection
    }
    if let observation {
      let resetElapsed = observation.values.weekly.resetAt.map({ $0 <= now }) ?? true
      let stale = now.timeIntervalSince(observation.capturedAt) > Self.observationMaximumAge
      if resetElapsed || stale {
        self.observation = nil
        if state == .current { state = resetElapsed ? .resetElapsed : .stale }
      }
    }
    return true
  }

  private mutating func invalidate(_ state: DesktopUsageState) {
    observation = nil
    activeRequest = nil
    context = nil
    suspendedState = nil
    // Preserve generation rejection through a momentarily unavailable context.
    self.state = state
  }

  private func rejection(for generation: UUID) -> DesktopUsageState? {
    rejectedGenerations.last(where: { $0.generation == generation })?.state
  }

  private mutating func reject(_ generation: UUID, state: DesktopUsageState) {
    rejectedGenerations.removeAll { $0.generation == generation }
    rejectedGenerations.append((generation, state))
    rejectedGenerations = Array(rejectedGenerations.suffix(8))
  }

  private mutating func checkClock(_ now: Date) -> Bool {
    if Self.validDate(now) {
      let previousClock = latestClock
      latestClock = now
      if let previousClock, now < previousClock {
        // Rebase only local relative waits. Require a stable minute (or the
        // remaining backoff, up to 15 minutes); never shorten a service deadline.
        let remaining =
          [localNextAllowedAt, successfulNextAllowedAt].compactMap { $0 }.max()?
          .timeIntervalSince(previousClock) ?? 0
        localNextAllowedAt = now.addingTimeInterval(max(60, min(remaining, 900)))
        successfulNextAllowedAt = nil
      } else {
        return true
      }
    }
    observation = nil
    activeRequest = nil
    state = .invalidClock
    return false
  }

  private mutating func fail(_ state: DesktopUsageState, now: Date) {
    failureCount = min(failureCount + 1, 5)
    let interval = min(60 * pow(2, Double(failureCount - 1)), 900)
    extendDelay(until: now.addingTimeInterval(interval))
    self.state = state
    // Retain the original observation time only; never refresh or extend its reset.
  }

  private static func validDate(_ date: Date) -> Bool {
    date.timeIntervalSince1970.isFinite && date.timeIntervalSince1970 > 0
  }

  private mutating func extendDelay(until date: Date) {
    localNextAllowedAt = max(localNextAllowedAt ?? date, date)
  }

  private mutating func extendServiceDelay(until date: Date) {
    serviceNotBefore = max(serviceNotBefore ?? date, date)
  }

  private static func currentWindows(_ values: DesktopUsageValues, now: Date) -> DesktopUsageValues
  {
    DesktopUsageValues(
      weekly: values.weekly,
      fiveHour: values.fiveHour.flatMap { window in
        window.resetAt.map({ $0 > now }) == true ? window : nil
      })
  }
}
