import Foundation

// Pure admission/acceptance state machine. The isolated service supplies verified
// reader/transport metadata; no shipped application depends on this target.
struct DesktopUsageOwner: Equatable, Sendable {
  let accountFingerprint: String
  let organizationFingerprint: String

  var isValid: Bool {
    [accountFingerprint, organizationFingerprint].allSatisfy { value in
      value.utf8.count == 64
        && value.utf8.allSatisfy { (48...57).contains($0) || (97...102).contains($0) }
    }
  }
}

struct DesktopUsageContext: Equatable, Sendable {
  let owner: DesktopUsageOwner
  // Opaque revision generated by the reader, never a credential or its hash.
  // Must change on sign-out, account/org switching (including A -> B -> A), or renewal.
  let generation: UUID
  let expiresAt: Date
  let hasProfileScope: Bool
}

struct DesktopUsageRequest: Equatable, Sendable {
  let id: UUID
  let context: DesktopUsageContext
  let startedAt: Date
  let deadline: Date
}

struct DesktopUsageObservation: Equatable, Sendable {
  let owner: DesktopUsageOwner
  let capturedAt: Date
  let values: DesktopUsageValues
}

enum DesktopUsagePermission: Sendable {
  case notRequested
  case allowed
  case denied
}

enum DesktopUsageState: String, Sendable {
  case consentRequired
  case permissionDenied
  case identityUnavailable
  case contextChanged
  case credentialExpired
  case missingScope
  case ready
  case requesting
  case current
  case stale
  case resetElapsed
  case waitingForDesktopRenewal
  case accessDenied
  case rateLimited
  case temporaryFailure
  case timedOut
  case invalidResponse
  case identityMismatch
  case invalidClock
}

enum DesktopUsageReply: Sendable {
  // The transport must verify the profile with the same exact credential
  // lease as this usage request, disable redirects/cache, and bound bytes in transit.
  case response(
    status: Int, profileOwner: DesktopUsageOwner?, serverDate: Date?,
    cacheAge: TimeInterval?, retryAfter: Date?, body: Data)
  case networkFailure
  case timeout
}

struct DesktopUsageCoordinator: Sendable {
  static let requestTimeout: TimeInterval = 30
  static let refreshInterval: TimeInterval = 5 * 60
  static let observationMaximumAge: TimeInterval = 15 * 60

  private(set) var permission: DesktopUsagePermission = .notRequested
  private(set) var state: DesktopUsageState = .consentRequired
  private(set) var observation: DesktopUsageObservation?
  private(set) var activeRequest: DesktopUsageRequest?
  private(set) var lastAttemptAt: Date?
  private(set) var nextAllowedAt: Date?
  private var context: DesktopUsageContext?
  private var rejectedGenerations: [(generation: UUID, state: DesktopUsageState)] = []
  private var issuedRequests: [DesktopUsageRequest] = []
  private var failureCount = 0
  private var latestClock: Date?

  // Only explicit user interaction may change this; a polling caller cannot prompt.
  mutating func setPermission(_ permission: DesktopUsagePermission) {
    self.permission = permission
    observation = nil
    activeRequest = nil
    context = nil
    rejectedGenerations = []
    state = permission == .allowed ? .ready : permissionState
    // A permission toggle never bypasses an outstanding service backoff.
  }

  mutating func begin(context newContext: DesktopUsageContext?, now: Date) -> DesktopUsageRequest? {
    guard checkClock(now) else { return nil }
    guard synchronize(newContext, now: now) else { return nil }
    if let activeRequest {
      guard now >= activeRequest.deadline else { return nil }
      self.activeRequest = nil
      fail(.timedOut, now: now)
      return nil
    }
    if let context, let rejection = rejection(for: context.generation) {
      state = rejection
      return nil
    }
    guard nextAllowedAt.map({ now >= $0 }) ?? true, let context else { return nil }
    let request = DesktopUsageRequest(
      id: UUID(), context: context, startedAt: now,
      deadline: now.addingTimeInterval(Self.requestTimeout))
    activeRequest = request
    issuedRequests.append(request)
    issuedRequests = Array(issuedRequests.suffix(8))
    lastAttemptAt = now
    nextAllowedAt = now.addingTimeInterval(60)
    state = .requesting
    return request
  }

  mutating func complete(
    _ request: DesktopUsageRequest, reply: DesktopUsageReply,
    context newContext: DesktopUsageContext?, now: Date
  ) {
    // Cancelled replies cannot replace values. A known 429 may only extend the
    // service-wide delay, even when an account change revoked its request.
    guard let issuedIndex = issuedRequests.firstIndex(of: request) else { return }
    issuedRequests.remove(at: issuedIndex)
    // Authentication refusal belongs to the issued credential, independently of
    // whether current local files can be reread or this request was cancelled.
    if case .response(let status, _, _, _, _, _) = reply, status == 401 || status == 403 {
      reject(
        request.context.generation, state: status == 401 ? .waitingForDesktopRenewal : .accessDenied
      )
    }
    if case .response(429, _, _, _, let retryAfter, _) = reply {
      let receivedClock = Self.validDate(now) ? now : request.startedAt
      let conservativeClock = max(latestClock ?? request.startedAt, receivedClock)
      extendDelay(until: conservativeClock.addingTimeInterval(60))
      if let retryAfter, Self.validDate(retryAfter) { extendDelay(until: retryAfter) }
    }
    guard activeRequest == request else { return }
    guard checkClock(now), synchronize(newContext, now: now) else { return }
    guard activeRequest == request, context == request.context else { return }
    activeRequest = nil
    guard now < request.deadline else {
      fail(.timedOut, now: now)
      return
    }
    switch reply {
    case .networkFailure:
      fail(.temporaryFailure, now: now)
    case .timeout:
      fail(.timedOut, now: now)
    case .response(
      let status, let profileOwner, let serverDate, let cacheAge, let retryAfter, let body):
      if status == 401 || status == 403 {
        observation = nil
        state = status == 401 ? .waitingForDesktopRenewal : .accessDenied
        return
      }
      if status == 429 {
        fail(.rateLimited, now: now, retryAfter: retryAfter)
        return
      }
      guard status == 200 else {
        fail((500...599).contains(status) ? .temporaryFailure : .invalidResponse, now: now)
        return
      }
      if let rejection = rejection(for: request.context.generation) {
        observation = nil
        state = rejection
        return
      }
      guard profileOwner == request.context.owner else {
        observation = nil
        state = .identityMismatch
        reject(request.context.generation, state: state)
        return
      }
      guard let serverDate, Self.validDate(serverDate),
        serverDate >= request.startedAt.addingTimeInterval(-5),
        serverDate <= now, now.timeIntervalSince(serverDate) <= Self.requestTimeout + 5,
        cacheAge.map({ $0.isFinite && $0 == 0 }) ?? true,
        observation.map({ serverDate > $0.capturedAt }) ?? true,
        let values = try? DesktopUsagePayloadDecoder.decode(body, observedAt: serverDate),
        let reset = values.weekly.resetAt, reset > now
      else {
        fail(.invalidResponse, now: now)
        return
      }
      observation = DesktopUsageObservation(
        owner: request.context.owner, capturedAt: serverDate,
        values: Self.currentWindows(values, now: now))
      failureCount = 0
      state = .current
      extendDelay(until: min(reset, now.addingTimeInterval(Self.refreshInterval)))
    }
  }

  // Rechecking context is required even during backoff or a cached display read.
  mutating func currentObservation(
    context newContext: DesktopUsageContext?, now: Date
  ) -> DesktopUsageObservation? {
    guard checkClock(now), synchronize(newContext, now: now), let observation,
      observation.capturedAt <= now,
      now.timeIntervalSince(observation.capturedAt) <= Self.observationMaximumAge,
      let reset = observation.values.weekly.resetAt, reset > now
    else { return nil }
    return DesktopUsageObservation(
      owner: observation.owner, capturedAt: observation.capturedAt,
      values: Self.currentWindows(observation.values, now: now))
  }

  private var permissionState: DesktopUsageState {
    permission == .denied ? .permissionDenied : .consentRequired
  }

  private mutating func synchronize(_ newContext: DesktopUsageContext?, now: Date) -> Bool {
    guard permission == .allowed else {
      invalidate(permissionState)
      return false
    }
    guard let newContext, newContext.owner.isValid else {
      invalidate(.identityUnavailable)
      return false
    }
    if newContext != context {
      let sameOwner = newContext.owner == context?.owner
      activeRequest = nil
      if !sameOwner { observation = nil }
      context = newContext
      state = .contextChanged
    }
    guard Self.validDate(newContext.expiresAt), newContext.expiresAt > now else {
      observation = nil
      activeRequest = nil
      state = .credentialExpired
      return false
    }
    guard newContext.hasProfileScope else {
      observation = nil
      activeRequest = nil
      state = .missingScope
      return false
    }
    if let rejection = rejection(for: newContext.generation) {
      observation = nil
      state = rejection
    }
    if let observation {
      let resetElapsed = observation.values.weekly.resetAt.map({ $0 <= now }) ?? true
      let stale = now.timeIntervalSince(observation.capturedAt) > Self.observationMaximumAge
      if resetElapsed || stale {
        self.observation = nil
        if state == .current { state = resetElapsed ? .resetElapsed : .stale }
      }
    }
    return true
  }

  private mutating func invalidate(_ state: DesktopUsageState) {
    observation = nil
    activeRequest = nil
    context = nil
    // Preserve generation rejection through a momentarily unavailable context.
    self.state = state
  }

  private func rejection(for generation: UUID) -> DesktopUsageState? {
    rejectedGenerations.last(where: { $0.generation == generation })?.state
  }

  private mutating func reject(_ generation: UUID, state: DesktopUsageState) {
    rejectedGenerations.removeAll { $0.generation == generation }
    rejectedGenerations.append((generation, state))
    rejectedGenerations = Array(rejectedGenerations.suffix(8))
  }

  private mutating func checkClock(_ now: Date) -> Bool {
    guard Self.validDate(now), latestClock.map({ now >= $0 }) ?? true else {
      observation = nil
      activeRequest = nil
      state = .invalidClock
      return false
    }
    latestClock = now
    return true
  }

  private mutating func fail(
    _ state: DesktopUsageState, now: Date, retryAfter: Date? = nil
  ) {
    failureCount = min(failureCount + 1, 5)
    let interval = min(60 * pow(2, Double(failureCount - 1)), 900)
    let earliest = now.addingTimeInterval(interval)
    if let retryAfter, Self.validDate(retryAfter), retryAfter > earliest {
      extendDelay(until: retryAfter)
    } else {
      extendDelay(until: earliest)
    }
    self.state = state
    // Retain the original observation time only; never refresh or extend its reset.
  }

  private static func validDate(_ date: Date) -> Bool {
    date.timeIntervalSince1970.isFinite && date.timeIntervalSince1970 > 0
  }

  private mutating func extendDelay(until date: Date) {
    nextAllowedAt = max(nextAllowedAt ?? date, date)
  }

  private static func currentWindows(_ values: DesktopUsageValues, now: Date) -> DesktopUsageValues
  {
    DesktopUsageValues(
      weekly: values.weekly,
      fiveHour: values.fiveHour.flatMap { window in
        window.resetAt.map({ $0 > now }) == true ? window : nil
      })
  }
}
